version: "3.0"  
services:  
  rasa:  
    image: rasa/rasa:latest
    ports:   
      - 5005:5005  
    volumes:   
      - ./:/app  
    command:  
      - run  
  app:  
    image: bot3:latest  
    ports:  
      - 5055:5055  